# Generated by Django 6.1 on 2026-08-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cluster_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cluster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cluster', 'name'), name='unique_namespace_per_cluster')],
            },
        ),
    ]
