# Generated by Django 6.1 on 2026-08-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.namespace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('namespace', 'name'), name='unique_app_per_namespace')],
            },
        ),
    ]
