# Generated by Django 6.1 on 2026-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backup_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
