# Generated by Django 6.1 on 2026-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_backupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
