apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: hamamooz

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi
